name: Basic CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Environment Check
        run: |
          echo "Checking environment..."
          echo "Working Directory: $(pwd)"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Name: ${{ runner.name }}"

      - name: Deploy Application
        run: |
          echo "Starting deployment..."
          docker-compose down
          docker-compose up -d --build
          echo "Deployment completed"

      - name: Verify Deployment
        run: |
          echo "Verifying containers..."
          docker ps
          echo "Deployment verification completed"
