name: Local CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests'
        required: true
        default: 'local'

jobs:
  local-ci:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
          cache: true
          cache-dependency-path: back/go.sum

      - name: Install dependencies
        working-directory: ./back
        run: |
          go mod download
          go mod verify

      - name: Run tests
        working-directory: ./back
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Lint and Vet
        working-directory: ./back
        run: |
          go vet ./...
          golangci-lint run

      - name: Build Docker images
        working-directory: ./back
        run: |
          docker build -t anb-showcase-api:local -f Dockerfile.api .
          docker build -t anb-showcase-worker:local -f Dockerfile.worker .

      - name: Coverage report
        working-directory: ./back
        run: |
          go tool cover -html=coverage.txt -o coverage.html

      - name: Store test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            back/coverage.html
            back/coverage.txt
          retention-days: 5
